import { Invoice, Contact, Product, DashboardMetric } from '../types';

// Mock data for dashboard metrics
export const mockDashboardMetrics: DashboardMetric[] = [
  {
    id: '1',
    label: 'Total Revenue',
    value: 125000,
    change: 12.5,
    period: 'vs last month',
  },
  {
    id: '2',
    label: 'Outstanding Invoices',
    value: 42000,
    change: -5.3,
    period: 'vs last month',
  },
  {
    id: '3',
    label: 'New Customers',
    value: 23,
    change: 15.2,
    period: 'vs last month',
  },
  {
    id: '4',
    label: 'Product Sales',
    value: 187,
    change: 8.7,
    period: 'vs last month',
  },
];

// Mock data for invoices
export const mockInvoices: Invoice[] = [
  {
    id: '1',
    number: 'INV-2023-001',
    date: '2023-01-10',
    dueDate: '2023-02-10',
    contactId: '1',
    status: 'paid',
    items: [
      {
        id: '1',
        productId: '1',
        description: 'Web Development Services',
        quantity: 1,
        price: 2500,
        subtotal: 2500,
      },
    ],
    total: 2500,
  },
  {
    id: '2',
    number: 'INV-2023-002',
    date: '2023-02-15',
    dueDate: '2023-03-15',
    contactId: '2',
    status: 'sent',
    items: [
      {
        id: '2',
        productId: '2',
        description: 'Logo Design',
        quantity: 1,
        price: 800,
        subtotal: 800,
      },
      {
        id: '3',
        productId: '3',
        description: 'Business Cards',
        quantity: 100,
        price: 2,
        subtotal: 200,
      },
    ],
    total: 1000,
  },
  {
    id: '3',
    number: 'INV-2023-003',
    date: '2023-03-01',
    dueDate: '2023-04-01',
    contactId: '3',
    status: 'overdue',
    items: [
      {
        id: '4',
        productId: '4',
        description: 'Monthly Maintenance',
        quantity: 1,
        price: 500,
        subtotal: 500,
      },
    ],
    total: 500,
  },
  {
    id: '4',
    number: 'INV-2023-004',
    date: '2023-03-15',
    dueDate: '2023-04-15',
    contactId: '1',
    status: 'draft',
    items: [
      {
        id: '5',
        productId: '5',
        description: 'E-commerce Integration',
        quantity: 1,
        price: 1500,
        subtotal: 1500,
      },
    ],
    total: 1500,
  },
  {
    id: '5',
    number: 'INV-2023-005',
    date: '2023-04-05',
    dueDate: '2023-05-05',
    contactId: '4',
    status: 'sent',
    items: [
      {
        id: '6',
        productId: '6',
        description: 'SEO Services',
        quantity: 1,
        price: 750,
        subtotal: 750,
      },
    ],
    total: 750,
  },
];

// Mock data for contacts
export const mockContacts: Contact[] = [
  {
    id: '1',
    name: 'Acme Inc.',
    email: 'billing@acme.com',
    phone: '+1 (555) 123-4567',
    type: 'customer',
    address: '123 Main St',
    city: 'San Francisco',
    postalCode: '94105',
    country: 'USA',
    notes: 'Key client since 2020',
  },
  {
    id: '2',
    name: 'TechStart LLC',
    email: 'accounts@techstart.io',
    phone: '+1 (555) 987-6543',
    type: 'customer',
    address: '456 Market St',
    city: 'New York',
    postalCode: '10001',
    country: 'USA',
  },
  {
    id: '3',
    name: 'Global Designs',
    email: 'finance@globaldesigns.com',
    phone: '+1 (555) 456-7890',
    type: 'customer',
    address: '789 Broadway',
    city: 'Los Angeles',
    postalCode: '90015',
    country: 'USA',
  },
  {
    id: '4',
    name: 'Paper Supplies Ltd',
    email: 'orders@papersupplies.co.uk',
    phone: '+44 (0) 20 7123 4567',
    type: 'vendor',
    address: '10 Oxford Street',
    city: 'London',
    postalCode: 'W1D 1BS',
    country: 'UK',
  },
  {
    id: '5',
    name: 'Cloud Hosting Services',
    email: 'billing@cloudhosting.com',
    phone: '+1 (555) 234-5678',
    type: 'vendor',
    address: '567 Cloud Ave',
    city: 'Seattle',
    postalCode: '98109',
    country: 'USA',
  },
];

// Mock data for products
export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'Web Development',
    description: 'Custom website development services',
    price: 2500,
    stock: 999,
    sku: 'SRV-WEB-001',
    category: 'Services',
  },
  {
    id: '2',
    name: 'Logo Design',
    description: 'Professional logo design with unlimited revisions',
    price: 800,
    stock: 999,
    sku: 'SRV-DES-001',
    category: 'Services',
  },
  {
    id: '3',
    name: 'Business Cards',
    description: 'Premium business cards, 350gsm, matte finish',
    price: 2,
    stock: 5000,
    sku: 'PRD-PRT-001',
    category: 'Printing',
  },
  {
    id: '4',
    name: 'Website Maintenance',
    description: 'Monthly website maintenance and updates',
    price: 500,
    stock: 999,
    sku: 'SRV-MNT-001',
    category: 'Services',
  },
  {
    id: '5',
    name: 'E-commerce Integration',
    description: 'Integration of e-commerce functionality into existing websites',
    price: 1500,
    stock: 999,
    sku: 'SRV-ECM-001',
    category: 'Services',
  },
  {
    id: '6',
    name: 'SEO Package',
    description: 'Complete SEO optimization package',
    price: 750,
    stock: 999,
    sku: 'SRV-SEO-001',
    category: 'Services',
  },
];